[workspace]
[package]
version = "0.1.0"
name = "rv_price-program"
edition = "2021"

[dependencies]
alloy-sol-types = "0.7.5"
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", tag = "v1.0.4-testnet" }