[package]
name = "axiom"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axiom-sdk = "0.1.1"
env_logger = "0.11.5"
halo2-base = "0.4.1"
num-bigint = "0.4.6"
num-integer = "0.1.46"
serde = "1.0.208"
serde_json = "1.0.127"
